version: '3'

volumes:
  postgres_data:
      driver: local
  jenkins_data:
      driver: local
  keycloak_data:
      driver: local

services:
  postgres:
      image: postgres:9.6
      container_name: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password

  keycloak:
      image: jboss/keycloak:3.4.3.Final
      container_name: keycloak
      environment:
        POSTGRES_PORT_5432_TCP_ADDR: postgres
        POSTGRES_PORT_5432_TCP_PORT: 5432
        POSTGRES_DATABASE: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: admin
        # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
        #JDBC_PARAMS: "ssl=true"
      ports:
        - 8080:8080
      depends_on:
        - postgres
      volumes:
        - keycloak_data:/data

  jenkins:
      image: openshift/jenkins-2-centos7:latest
      container_name: jenkins
      environment:
        JENKINS_PASSWORD: admin
        INSTALL_PLUGINS: blueocean:1.5.0, blueocean-rest:1.5.0,blueocean-git-pipeline:1.5.0,display-url-api:2.2.0,pubsub-light:1.12,
                         credentials:2.1.14,cloudbees-folder:6.1.2,branch-api:2.0.11,workflow-multibranch:2.16, structs:1.10,scm-api:2.2.6,
                         workflow-step-api:2.14,workflow-api:2.25,workflow-support:2.18,token-macro:2.1,git-client:2.7.0,
                         icon-shim:2.0.3,maven-plugin:2.17,ace-editor:1.0.1,analysis-core:1.92,analysis-collector:1.52,
                         authentication-tokens:1.1,checkstyle:3.49,conditional-buildstep:1.3.1,config-file-provider:2.16.2,
                         dependency-check-jenkins-plugin:2.1.1,docker-commons:1.8,docker-workflow:1.9,durable-task:1.16,
                         favorite:2.3.1,findbugs:4.71,gerrit-trigger:2.27.5,github-api:1.86,github-branch-source:2.2.3,
                         github:1.26.0,git:3.8.0,git-server:1.5,handlebars:1.1,jackson2-api:2.7.3,jacoco:2.2.1,javadoc:1.0,job-dsl:1.60,
                         jquery:1.11.2-0,junit:1.23,mapdb-api:1.0.1.0,matrix-auth:1.7,matrix-project:1.7.1,mercurial:2.3,
                         metrics:3.1.2.9,momentjs:1.1,parameterized-trigger:2.35.1,pipeline-build-step:2.7,pipeline-graph-analysis:1.6,
                         pipeline-milestone-step:1.3.1,pipeline-model-api:1.2.7,pipeline-model-definition:1.2.7,pipeline-model-extensions:1.2.7,
                         pipeline-stage-step:2.2,pipeline-stage-tags-metadata:1.2.7,pipeline-stage-view:2.4,plain-credentials:1.3,pmd:3.49,
                         run-condition:0.10,sonar-gerrit:2.1,subversion:2.9,workflow-basic-steps:2.3,workflow-cps-global-lib:2.7,
                         workflow-cps:2.42,workflow-durable-task-step:2.13,workflow-job:2.14.1, workflow-remote-loader:1.2,workflow-scm-step:2.4,
                         htmlpublisher:1.14,test-results-analyzer:0.3.4,sonar:2.7.1,role-strategy:2.7.0
                         greenballs:1.15,keycloak:2.2.0,validating-string-parameter:2.3
      ports:
        - '8081:8080'
        - "50000:50000"
      volumes:
        - 'jenkins_data:/jenkins'
